@BASE_URL = http://localhost:3333

# @name create-account
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "name": "Reinaldo",
  "email": "contato@reinaldodev.com.br",
  "password": "P@$$w0rd"
}
