@BASE_URL = http://localhost:3333

# @name create-account
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "name": "Reinaldo",
  "email": "contato@reinaldodev.com.br",
  "password": "P@$$w0rd"
}

###

# @name authenticade-with-password
POST {{BASE_URL}}/sessions/password
Content-Type: application/json

{
  "name": "Reinaldo",
  "email": "contato@reinaldodev.com.br",
  "password": "123456"
}

###

# @name get-profile
GET {{BASE_URL}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNDFiNTkyNC1kYjFjLTRkZGItOGEwYi1jZGQzZWJhMmY0ZmUiLCJpYXQiOjE3MTU3NzY1NDgsImV4cCI6MTcxNjM4MTM0OH0.Dy_HpEwVm4MiN7EjJFzcaQWTZr-5f8eUEQ94cF1dWGk
